// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIbP-WQ6XQYoda1SqvLGjPodXvW_PrHt0',
    appId: '1:914817987535:android:1e20d95e0f41cf142858ba',
    messagingSenderId: '914817987535',
    projectId: 'tesis2025re',
    storageBucket: 'tesis2025re.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5hGTwIF-q-EMwjz2e9EjMShzNbfC2x2A',
    appId: '1:914817987535:ios:70f7e13ed09ab9662858ba',
    messagingSenderId: '914817987535',
    projectId: 'tesis2025re',
    storageBucket: 'tesis2025re.firebasestorage.app',
    androidClientId: '914817987535-il4rtskknoaauiikv0k53e8j1gd4qg2t.apps.googleusercontent.com',
    iosClientId: '914817987535-r0g9drf0c9ktdbc423fsulvo9bp3n8cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesis',
  );
}
